---
title: "Explore scenario analysis"
output: html_document
date: "2024-11-25"
editor_options: 
  chunk_output_type: console
---

## Summary

Create tables that we will provide in the supplementary material of the manuscript.

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(glue)
library(sf)
library(devtools)
library(janitor)
library(countrycode)
library(qs)
library(scales)
library(viridis)
library(dplyr)
library(exploreARTIS)
library(patchwork)
library(ggsankey)
library(stringr)


source(here("R/directories.R"))

fm_data_adjusted <-   qs::qread(file.path(artis_dir, "artis_exchange/artis_fishmeal_trimmings_traded_consumption_gf_final.qs"))

artis_taxa <- read.csv(file.path(artis_dir, "artis_full_data/data/attribute tables/sciname.csv")) %>% ## read in attribute table with common names
  mutate(phylum = case_when(
    common_name %in% c("mackerels, tunas, and bonitos", "salmons and trouts", "herrings", "cartilaginous fishes nei", "flounders", "african lungfishes", "toothfish", "carps, minnows, loaches, etc", "blue whitings") ~ "chordata",
    TRUE ~ phylum
  )) # fix phylum mistakes
```



Save SI Tables

```{r}
codes <- read.csv(file.path(artis_dir, "artis_full_data/data/attribute tables/products.csv"))

fillet_codes <- codes %>% 
  filter(presentation == "fillet") %>%
      mutate(hs6 = as.character(hs6)) %>%
    mutate(hs6 = case_when(
      str_length(hs6) == 5 ~ paste("0", hs6, sep = ""),
      TRUE ~ hs6
    )) %>%
  distinct(hs6, description)

write.csv(fillet_codes, here("outputs/SI_table_fillets.csv"), row.names = FALSE)


SI_Table_2 <- read.csv(here("int/material_origins_ALL.csv")) %>%
  dplyr::select(common_name, sciname, `Species name from report/literature` = feed_report_spp_name, source_country_name, source_country_iso3c, processor_iso3c = importer_iso3c, wholefish, trimmings, `Proportion of production which is trimmings derived` = trim_prop, Source = data_source_feed) %>%
  mutate(Source = case_when(
    Source == "skretting" ~ "Skretting 2022", 
    Source == "cargill" ~ "Cargill 2023", 
    Source == "biomar" ~ "Biomar 2023", 
    TRUE ~ Source
  ))

write.csv(SI_Table_2, here("outputs/SI/SI_Table_2.csv"), row.names = FALSE)

SI_Table_3 <- read.csv(here("int/material_origins_ALL.csv")) %>%
  filter(data_source_feed %in% c("biomar", "skretting", "cargill")) %>%
  group_by(common_name, sciname, source_country_iso3c, source_country_name) %>%
  summarise(trim_prop = mean(trim_prop, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(trimmings = ifelse(trim_prop > 0, "yes", "no")) %>%
  mutate(whole_fish = ifelse(trim_prop < 1, "yes", "no"))
  

write.csv(SI_Table_3, here("outputs/SI/SI_Table_3.csv"), row.names = FALSE)

SI_Table_4 <- read.csv(here("int/material_origins_ALL.csv")) %>%
  filter(!(data_source_feed %in% c("biomar", "skretting", "cargill"))) %>%
  group_by(common_name, sciname, source_country_iso3c, source_country_name) %>%
  summarise(trim_prop = mean(trim_prop, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(trimmings = ifelse(trim_prop > 0, "yes", "no")) %>%
  mutate(whole_fish = ifelse(trim_prop < 1, "yes", "no"))
  

write.csv(SI_Table_4, here("outputs/SI/SI_Table_4.csv"), row.names = FALSE)

fm_data_adjusted <- qs::qread(here("outputs/top_species_fm_1996_2020.qs"))

total_2020 <- fm_data_adjusted %>%
  filter(year == 2020) %>%
  pull(product_weight_t) %>%
  sum()

si_table_5 <- fm_data_adjusted %>%
  filter(year == 2020) %>%
  group_by(`Gapfilling assumption` = method_trim_gf) %>%
  summarise(`Product accounted for (as percentage of ARTIS total, 2020)` = round((sum(product_weight_t, na.rm = TRUE)/total_2020)*100, 2),
            `Number of distinct species` = n_distinct(sciname),
            `Number of distinct countries` = n_distinct(source_country_iso3c)) %>%
 # filter(!(`Gapfilling assumption` %in% c("wild caught salmon trimmings", "barnacle"))) %>%
  mutate(Source = 
           case_when(
             `Gapfilling assumption` %in% c("Asian trash fish assumption") ~ "Majluf et al. 2024",
             `Gapfilling assumption` %in% c("Assuming trimmings because production method is aquaculture") ~ "Bachis 2024; Skretting 2022; Xu & Ming 2018; Ytrestøyl et al. 2015, Penarubia et al. 2023",
             `Gapfilling assumption` %in% c("Assuming trimmings because these are shrimp or prawn") ~ "Bachis 2024; Hertrampf et al. 2000",
             `Gapfilling assumption` %in% c("Average trimmings proportion of genus from literature and reports") ~ "See SI Tables 2-4",
             `Gapfilling assumption` %in% c("Average trimmings proportion of source country and species from literature and reports") ~ "See SI Tables 2-3",
             `Gapfilling assumption` %in% c("Average trimmings proportion of species from literature and reports") ~ "See SI Tables 2-4",
             `Gapfilling assumption` %in% c("Average trimmings proportion per country from known data") ~ "See SI Tables 2-4",
             `Gapfilling assumption` %in% c("gapfilled whole fish because average price is lower than 3-year average whole fish price") ~ "Melnychuk et al. 2017",
             `Gapfilling assumption` %in% c("Lobster, crab, or other crustaceans assumed trimmings") ~ "Bachis 2024; Hertrampf et al. 2000",
             `Gapfilling assumption` == "Assuming trimmings because these are squids, octopus, or cuttlefish" ~ "Bachis 2024; Hertrampf et al. 2000",
             `Gapfilling assumption` %in% c("Used fillet data to determine proportion of fishmeal which is trimmings") ~ "Gephart et al. 2024",
         `Gapfilling assumption` %in% c("wild caught salmon trimmings") ~ "Bachis 2024"
           )) %>%
  mutate(Source = ifelse(is.na(Source), "See SI Tables 2-4", Source)) %>%
  mutate(`Gapfilling step` = 
           case_when(
             `Gapfilling assumption` == "none; filled using company reports from source to processing country" ~ 1,
             `Gapfilling assumption` == "none; filled using values from literature" ~ 2,      
             `Gapfilling assumption` == "Average trimmings proportion of source country and species from all literature and reports" ~ 3,                
             `Gapfilling assumption` == "Assuming trimmings because production method is aquaculture" ~ 4,   
             `Gapfilling assumption` == "Average trimmings proportion of species from literature and reports" ~ 5,          
             `Gapfilling assumption` == "Used fillet data to determine proportion of fishmeal which is trimmings" ~ 6,          
             `Gapfilling assumption` == "Assuming trimmings because these are shrimp or prawn" ~ 7,     
             `Gapfilling assumption` == "Assuming trimmings because these are squids, octopus, or cuttlefish" ~ 8,               
             `Gapfilling assumption` == "gapfilled whole fish because average price is lower than 3-year average whole fish price" ~ 9,                   `Gapfilling assumption` == "Average trimmings proportion of genus from literature and reports" ~ 10,          
             `Gapfilling assumption` == "Asian trash fish assumption" ~ 11,               
             `Gapfilling assumption` == "Lobster, crab, or other crustaceans assumed trimmings" ~ 12,               
             `Gapfilling assumption` == "wild caught salmon trimmings" ~ 13,               
             `Gapfilling assumption` == "Average trimmings proportion per country from known data" ~ 14,               
             )) %>%
    arrange(`Gapfilling step`)


write.csv(si_table_5, here("outputs/SI/SI_Table_5.csv"), row.names = FALSE)

```

```{r}
library(openxlsx)

# Create a new workbook
wb <- createWorkbook()

# Add each CSV as a worksheet
addWorksheet(wb, "SI_Table_1")
writeData(wb, "SI_Table_1", read.csv(here("outputs/SI_table_fillets.csv")))

addWorksheet(wb, "SI_Table_2")
writeData(wb, "SI_Table_2", read.csv(here("outputs/SI/SI_Table_2.csv")))

addWorksheet(wb, "SI_Table_3")
writeData(wb, "SI_Table_3", read.csv(here("outputs/SI/SI_Table_3.csv")))

addWorksheet(wb, "SI_Table_4")
writeData(wb, "SI_Table_4", read.csv(here("outputs/SI/SI_Table_4.csv")))

addWorksheet(wb, "SI_Table_5")
writeData(wb, "SI_Table_5", read.csv(here("outputs/SI/SI_Table_5.csv")))

# Save the workbook
saveWorkbook(wb, here("outputs/SI/Extended data.xlsx"), overwrite = TRUE)


```


Make an SI plot with non-gapfilled data

```{r}
non_gf <- qs::qread(here("int/non_gapfilled_fishmeal_matched.qs"))

fm_data_adjusted <- non_gf %>%
  left_join(artis_taxa) %>%
      mutate(phylum = case_when(is.na(phylum) & sciname %in% c("lampetra fluviatilis", "petromyzontidae", "petromyzon marinus") ~ "chordata",
                              is.na(phylum) & sciname == "animalia" ~ "animalia",
                            TRUE ~ phylum)) %>% 
    filter(phylum %in% c("chordata", "arthropoda") | phylum == "mollusca" & class == "cephalopoda") %>%
    mutate(trimmings = live_weight_t*trim_prop_gf,
         wholefish = live_weight_t*(1-trim_prop_gf)) %>%
  dplyr::select(-product_weight_t, -live_weight_t, -capture) %>%
  pivot_longer( 
    cols = c(trimmings, wholefish),
    names_to = "fishmeal_type",
    values_to = "live_weight_t"
  ) %>%
  mutate(product_weight_t =
           case_when(
             phylum == "arthropoda" & fishmeal_type == "trimmings" ~ (live_weight_t*0.98)/2.975207,
             phylum %in% c("mollusca", "chordata") & fishmeal_type == "trimmings" ~ (live_weight_t*0.96)/2.975207,
             TRUE ~ live_weight_t/2.975207
           )) 

## now save every year of data 1996-2020 with only top 20 species
# fm_data_top_spp <- fm_data_adjusted %>%
#     group_by(year, source_country_iso3c, exporter_iso3c, importer_iso3c = consumer_iso3c, sciname, common_name, fishmeal_type, phylum) %>%
#     summarise(
#       product_weight_t = sum(product_weight_t, na.rm = TRUE),
#             live_weight_t = sum(live_weight_t, na.rm = TRUE)
# 
#     ) %>%
#     ungroup() %>%
#   group_by(source_country_iso3c, sciname) %>% 
#   summarise(total_product_weight = sum(product_weight_t, na.rm = TRUE), .groups = "drop") %>%
#   arrange(source_country_iso3c, desc(total_product_weight)) %>%
#   group_by(source_country_iso3c) %>%
#   slice_head(n = 20) %>% # take the top 20 species for each source country (and year?)
#   ungroup() %>%
#   right_join(fm_data_adjusted, by = c("source_country_iso3c", "sciname")) %>%
#     filter(!is.na(total_product_weight)) %>%
#     left_join(artis_taxa) # this takes awhile to run

all_spp_time <- fm_data_adjusted %>%
  group_by(year, fishmeal_type) %>%
  summarise(product_t = sum(product_weight_t, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(total_t = sum(product_t)) %>%
  ungroup() %>%
  mutate(prop = product_t/total_t) %>%
  mutate(data_type = "All species")

finfish_time <- fm_data_adjusted %>%
  filter(phylum == "chordata") %>%
  group_by(year, fishmeal_type) %>%
  summarise(product_t = sum(product_weight_t, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(total_t = sum(product_t)) %>%
  ungroup() %>%
  mutate(prop = product_t/total_t) %>%
  mutate(data_type = "Finfish") 

crust_time <- fm_data_adjusted %>%
  filter(phylum == "arthropoda") %>%
  group_by(year, fishmeal_type) %>%
  summarise(product_t = sum(product_weight_t, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(total_t = sum(product_t)) %>%
  ungroup() %>%
  mutate(prop = product_t/total_t) %>%
  mutate(data_type = "Crustaceans") 

mollusc_time <- fm_data_adjusted %>%
  filter(phylum == "mollusca") %>%
  group_by(year, fishmeal_type) %>%
  summarise(product_t = sum(product_weight_t, na.rm = TRUE)) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(total_t = sum(product_t)) %>%
  ungroup() %>%
  mutate(prop = product_t/total_t) %>%
  mutate(data_type = "Cephalopoda")  %>%
  filter(product_t != 0)

overtime_all <- rbind(all_spp_time, finfish_time, crust_time, mollusc_time) %>%
  mutate(perc = scales::percent(round(prop, 2), accuracy = 1))

artis_palette(length(unique(overtime_all$fishmeal_type)))

ggplot(overtime_all, aes(x = year, y = product_t, color = fishmeal_type)) +
  geom_line() +
  theme_bw() +
  facet_wrap(~data_type, scales = "free_x") + 
  labs(x = "Year", y = "Fishmeal product (million tonnes)", color = "Fishmeal type") + 
    scale_color_manual(values = c("trimmings" = "#741A32", "wholefish" = "#114F59"), 
                     labels = c("Trimmings-derived", "Whole fish-derived")) + 
  scale_x_continuous(limits = c(1994.5, 2021.5), breaks = c(1996, 2002, 2008, 2014, 2020), 
                     labels = c(1996, 2002, 2008, 2014, 2020)) +
  theme(legend.position = "bottom") +
  scale_y_continuous(labels = function(x) x/1e6,
                   name = "Fishmeal product (million tonnes)") + 
    geom_text(data = filter(overtime_all, year == 2020, fishmeal_type == "trimmings", !(data_type %in% c("Cephalopoda", "Crustaceans"))),
            aes(x = year, y = product_t, label = perc),
            vjust = 0, hjust = -0.1, show.legend = FALSE, size = 3) +
      geom_text(data = filter(overtime_all, year == 2020, fishmeal_type == "wholefish", data_type != "Cephalopoda"),
            aes(x = year, y = product_t, label = perc),
            vjust = 0, hjust = -0.1, show.legend = FALSE, size = 3) +
      geom_text(data = filter(overtime_all, year == 1996, fishmeal_type == "trimmings", data_type %in% c("All species", "Finfish")),
            aes(x = year, y = product_t, label = perc),
            vjust = 0, hjust = 1, show.legend = FALSE, size = 3) +
      geom_text(data = filter(overtime_all, year == 1996, fishmeal_type == "wholefish", data_type != "Crustaceans"),
            aes(x = year, y = product_t, label = perc),
            vjust = 0.2, hjust = 1, show.legend = FALSE, size = 3) +
        geom_text(data = filter(overtime_all, year == 1996, fishmeal_type == "trimmings", data_type == "Crustaceans"),
            aes(x = year, y = product_t, label = perc),
            vjust = 0, hjust = 1, show.legend = FALSE, size = 3) +
      # geom_text(data = filter(overtime_all, year == 1996, fishmeal_type == "wholefish", data_type == "Crustaceans"),
      #       aes(x = year, y = product_t, label = perc),
      #       vjust = 0.5, hjust = 1, show.legend = FALSE, size = 3)  + 
      geom_text(data = filter(overtime_all, year == 2020, fishmeal_type == "trimmings", data_type == "Cephalopoda"),
            aes(x = year, y = product_t, label = perc),
            vjust = -0.5, hjust = 0.2, show.legend = FALSE, size = 3)  + 
      geom_text(data = filter(overtime_all, year == 1996, fishmeal_type == "trimmings", data_type == "Cephalopoda"),
            aes(x = year, y = product_t, label = perc),
            vjust = -0.6, hjust = 0.8, show.legend = FALSE, size = 3) 

 
ggsave(here("outputs/figs/SI/SI_fig_2.png"), width = 180, height =180 , units = "mm", bg = "white", dpi =300)


```

